import "animate.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";

const generalSans = localFont({
  src: "../fonts/GeneralSans-Variable.woff",
  variable: "--font-general-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${generalSans.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
